# Generated by Django 4.0 on 2022-01-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PKRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('beds', models.IntegerField()),
                ('admitted_pui', models.IntegerField()),
                ('admitted_covid', models.IntegerField()),
                ('admitted_total', models.IntegerField()),
                ('discharged_pui', models.IntegerField()),
                ('discharged_covid', models.IntegerField()),
                ('discharged_total', models.IntegerField()),
                ('pkrc_covid', models.IntegerField()),
                ('pkrc_pui', models.IntegerField()),
                ('pkrc_noncovid', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='ICU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('beds_icu', models.IntegerField()),
                ('beds_icu_rep', models.IntegerField()),
                ('beds_icu_total', models.IntegerField()),
                ('beds_icu_covid', models.IntegerField()),
                ('vent', models.IntegerField()),
                ('vent_port', models.IntegerField()),
                ('icu_covid', models.IntegerField()),
                ('icu_pui', models.IntegerField()),
                ('icu_noncovid', models.IntegerField()),
                ('vent_covid', models.IntegerField()),
                ('vent_pui', models.IntegerField()),
                ('vent_noncovid', models.IntegerField()),
                ('vent_used', models.IntegerField()),
                ('vent_port_used', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('beds', models.IntegerField()),
                ('beds_covid', models.IntegerField()),
                ('beds_noncrit', models.IntegerField()),
                ('admitted_pui', models.IntegerField()),
                ('admitted_covid', models.IntegerField()),
                ('admitted_total', models.IntegerField()),
                ('discharged_pui', models.IntegerField()),
                ('discharged_covid', models.IntegerField()),
                ('discharged_total', models.IntegerField()),
                ('hosp_covid', models.IntegerField()),
                ('hosp_pui', models.IntegerField()),
                ('hosp_noncovid', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.state')),
            ],
        ),
    ]
