# Generated by Django 4.0 on 2022-01-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysj',
            name='checkins_to_ind_ratio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mysj',
            name='checkins_to_unique_loc_ratio',
            field=models.FloatField(),
        ),
    ]
