# Generated by Django 4.0 on 2022-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('state', models.IntegerField()),
                ('daily_partial', models.IntegerField()),
                ('daily_full', models.IntegerField()),
                ('daily', models.IntegerField()),
                ('daily_partial_child', models.IntegerField()),
                ('daily_full_child', models.IntegerField()),
                ('daily_booster', models.IntegerField()),
                ('cumul_partial', models.IntegerField()),
                ('cumul_full', models.IntegerField()),
                ('cumul', models.IntegerField()),
                ('cumul_partial_child', models.IntegerField()),
                ('cumul_full_child', models.IntegerField()),
                ('cumul_booster', models.IntegerField()),
                ('pfizer1', models.IntegerField()),
                ('pfizer2', models.IntegerField()),
                ('pfizer3', models.IntegerField()),
                ('sinovac1', models.IntegerField()),
                ('sinovac2', models.IntegerField()),
                ('sinovac3', models.IntegerField()),
                ('astra1', models.IntegerField()),
                ('astra2', models.IntegerField()),
                ('astra3', models.IntegerField()),
                ('sinopharm1', models.IntegerField()),
                ('sinopharm2', models.IntegerField()),
                ('sinopharm3', models.IntegerField()),
                ('cansino', models.IntegerField()),
                ('cansino3', models.IntegerField()),
                ('pending1', models.IntegerField()),
                ('pending2', models.IntegerField()),
                ('pending3', models.IntegerField()),
            ],
        ),
    ]
