from django.db import models
from core.models import State

class Vaccination(models.Model):
    date = models.DateField(db_index=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    daily_partial = models.IntegerField()
    daily_full = models.IntegerField()
    daily = models.IntegerField()
    daily_partial_child = models.IntegerField()
    daily_full_child = models.IntegerField()
    daily_booster = models.IntegerField()
    cumul_partial = models.IntegerField()
    cumul_full = models.IntegerField()
    cumul = models.IntegerField()
    cumul_partial_child = models.IntegerField()
    cumul_full_child = models.IntegerField()
    cumul_booster = models.IntegerField()
    pfizer1 = models.IntegerField()
    pfizer2 = models.IntegerField()
    pfizer3 = models.IntegerField()
    sinovac1 = models.IntegerField()
    sinovac2 = models.IntegerField()
    sinovac3 = models.IntegerField()
    astra1 = models.IntegerField()
    astra2 = models.IntegerField()
    astra3 = models.IntegerField()
    sinopharm1 = models.IntegerField()
    sinopharm2 = models.IntegerField()
    sinopharm3 = models.IntegerField()
    cansino = models.IntegerField()
    cansino3 = models.IntegerField()
    pending1 = models.IntegerField()
    pending2 = models.IntegerField()
    pending3 = models.IntegerField()
